export const event = '/game-event'
export const eventManager = '/game-event/event-manager'
export const eventScore = '/game-event/event-manager/score'
export const uploadEvent = '/game-event/upload-event'
export const bettingHistory = '/game-event/betting-history'
export const defaultOdds = '/game-event/default-odds'
export const eventRule = '/game-event/event-rule'

export const member = '/member'
export const memberActivity = '/member/activity'
export const memberManage = '/member/manage'
export const memberManageDetail = '/member/manage/detail'
export const memberLabel = '/member/label'

export const organization = '/organization'
export const organizationManage = '/organization/manage'

export const payment = '/payment'
export const BankDeposit = '/payment/bank/deposit'
export const ThirdPartyDeposit = '/payment/third-party/deposit'
export const Withdrawal = '/payment/withdrawal'
export const ManualPayment = '/payment/manual'
export const DepositSetting = '/payment/deposit-setting'
export const WithdrawalSetting = '/payment/withdrawal-setting'
export const BankAccountSetting = '/payment/bank/setting'
export const ThirdPartySetting = '/payment/third-party/setting'

export const report = '/report'
export const gameReport = '/report/game'
export const dailyReport = '/report/daily'
export const monthlyReport = '/report/monthly'

export const promote = '/promote'
export const promoteLink = '/promote/link'
export const promoteAcitivity = '/promote/activity'

export const admin = '/admin'
export const adminAccount = '/admin/account'
export const adminRole = '/admin/role'
export const adminHistory = '/admin/history'

export const system = '/system'
export const IpSetting = '/system/ip-setting'
export const LoginHistory = '/system/login-history'

export const website = '/website'
export const landingPage = '/website/landing-page'
export const carousel = '/website/carousel'
export const pageManage = '/website/page-manage'
export const announcement = '/website/announcement'
export const faq = '/website/faq'

export const version = '/version'
