export const Event = '/game-event'
export const EventManager = '/game-event/event-manager'
export const EventScore = '/game-event/event-manager/score'
export const UploadEvent = '/game-event/upload-event'
export const BettingHistory = '/game-event/betting-history'
export const DefaultOdds = '/game-event/default-odds'
export const EventRule = '/game-event/event-rule'

export const Member = '/member'
export const MemberActivity = '/member/activity'
export const MemberManage = '/member/manage'
export const MemberDetail = '/member/manage/detail'
export const MemberLabel = '/member/label'

export const Organization = '/organization'
export const OrganizationManage = '/organization/manage'
export const InvitationCode = '/organization/invitation-code'

export const Payment = '/payment'
export const BankDeposit = '/payment/bank/deposit'
export const ThirdPartyDeposit = '/payment/third-party/deposit'
export const Withdrawal = '/payment/withdrawal'
export const ManualPayment = '/payment/manual'
export const DepositSetting = '/payment/deposit-setting'
export const WithdrawalSetting = '/payment/withdrawal-setting'
export const BankAccountSetting = '/payment/bank/setting'
export const ThirdPartySetting = '/payment/third-party/setting'

export const Report = '/report'
export const GameReport = '/report/game'
export const DailyReport = '/report/daily'
export const MonthlyReport = '/report/monthly'

export const Promote = '/promote'
export const PromoteLink = '/promote/link'
export const PromoteAcitivity = '/promote/activity'
export const CreatePromoteAcitivity = '/promote/activity/create'
export const PromoteReview = '/promote/review'

export const Admin = '/admin'
export const AdminAccount = '/admin/account'
export const AdminRole = '/admin/role'
export const AdminHistory = '/admin/history'

export const System = '/system'
export const IpSetting = '/system/ip-setting'
export const LoginHistory = '/system/login-history'

export const Website = '/website'
export const LandingPage = '/website/landing-page'
export const Carousel = '/website/carousel'
export const PageManage = '/website/page-manage'
export const Announcement = '/website/announcement'
export const InMail = '/website/in-mail'
export const Faq = '/website/faq'

export const Version = '/version'
