build-testing:
  image: caixin0823/node
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  only:
    - dev
  tags:
    - blockchain
  artifacts:
    expire_in: 1 week
    paths:
      - public
      
deploy-testing:
  image: alpine
  stage: deploy
  script:
    - rsync -rav --delete -e 'ssh -p 2222' public/ $SERVER_TOKEN_TEST:$WEB_ROOT
  only:
    - dev
  tags:
    - blockchain
  before_script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_TEST" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod -R 600 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS_TEST" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

build-master:
  image: caixin0823/node
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  only:
    - master
  tags:
    - blockchain
  artifacts:
    expire_in: 1 week
    paths:
      - public
      
deploy-master:
  image: alpine
  stage: deploy
  script:
    - rsync -rav --delete -e 'ssh -p 2222' public/ $SERVER_TOKEN:$WEB_ROOT
  only:
    - master
  tags:
    - blockchain
  before_script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod -R 600 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
